# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19sGhTFS5yu5yMCKQ4xAPXLLYgwSnJb5N
"""

"""
00 - Exploratory Data Analysis
Understand the dataset before writing any scoring logic.

Steps:
1. Load a sample of candidates
2. Check data quality (nulls, ranges, distributions)
3. Understand the 23 Redrob signals
4. Spot honeypots manually
5. Read good vs bad candidate profiles
"""

# Install if needed (uncomment and run once in your terminal):
# pip install pandas numpy matplotlib seaborn

import json
import re
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path
from datetime import date, datetime
from collections import Counter

# ── Change this path to where your candidates.jsonl lives ──────────────────
CANDIDATES_FILE = Path("/content/candidates.jsonl")
SAMPLE_SIZE = 1000  # load first N candidates for EDA

plt.rcParams['figure.dpi'] = 110
sns.set_theme(style='whitegrid', palette='muted')
print(f"File exists: {CANDIDATES_FILE.exists()}")


# =============================================================================
# Step 1 - Load sample candidates
# =============================================================================

candidates = []
with open(CANDIDATES_FILE, 'r', encoding='utf-8') as f:
    for i, line in enumerate(f):
        if i >= SAMPLE_SIZE:
            break
        line = line.strip()
        if line:
            candidates.append(json.loads(line))

print(f"Loaded {len(candidates)} candidates")
print()
print("-- Raw structure of candidate #1 --")
c = candidates[0]
print(f"Top-level keys : {list(c.keys())}")
print(f"profile keys   : {list(c['profile'].keys())}")
print(f"career_history : {len(c['career_history'])} jobs - keys: {list(c['career_history'][0].keys()) if c['career_history'] else 'EMPTY'}")
print(f"skills         : {len(c['skills'])} skills - keys: {list(c['skills'][0].keys()) if c['skills'] else 'EMPTY'}")
print(f"education      : {len(c['education'])} entries")
print(f"certifications : {len(c['certifications'])} entries")
print(f"redrob_signals : {len(c['redrob_signals'])} signals")

# Print a single candidate in full so you can see what the raw data looks like
print(json.dumps(candidates[0], indent=2))


# =============================================================================
# Step 2 - Flatten into a DataFrame for analysis
# =============================================================================

def flatten(c):
    p = c['profile']
    rs = c['redrob_signals']
    sal = rs.get('expected_salary_range_inr_lpa') or {}
    career = c.get('career_history', [])
    skills = c.get('skills', [])
    edu = c.get('education', [])
    certs = c.get('certifications', [])

    # Derived fields
    total_career_months = sum(j.get('duration_months') or 0 for j in career)
    n_expert_skills = sum(1 for s in skills if s.get('proficiency') == 'expert')
    n_advanced_skills = sum(1 for s in skills if s.get('proficiency') == 'advanced')
    avg_skill_duration = np.mean([s.get('duration_months') or 0 for s in skills]) if skills else 0
    avg_job_tenure = total_career_months / len(career) if career else 0

    # Days since last active
    last_active = rs.get('last_active_date')
    try:
        days_inactive = (date.today() - datetime.strptime(last_active[:10], '%Y-%m-%d').date()).days if last_active else 9999
    except Exception:
        days_inactive = 9999

    return {
        'candidate_id': c['candidate_id'],
        # Profile
        'current_title': p.get('current_title', ''),
        'current_company': p.get('current_company', ''),
        'current_industry': p.get('current_industry', ''),
        'location': p.get('location', ''),
        'country': p.get('country', ''),
        'years_of_experience': p.get('years_of_experience'),
        'has_headline': bool(p.get('headline')),
        'has_summary': bool(p.get('summary')),
        # Career
        'n_jobs': len(career),
        'total_career_months': total_career_months,
        'avg_job_tenure_months': round(avg_job_tenure, 1),
        # Skills
        'n_skills': len(skills),
        'n_expert_skills': n_expert_skills,
        'n_advanced_skills': n_advanced_skills,
        'avg_skill_duration_months': round(avg_skill_duration, 1),
        # Education
        'n_education': len(edu),
        'highest_edu_tier': edu[0].get('tier', 'unknown') if edu else 'none',
        # Certifications
        'n_certifications': len(certs),
        # Signals
        'profile_completeness': rs.get('profile_completeness_score'),
        'days_inactive': days_inactive,
        'open_to_work': rs.get('open_to_work_flag'),
        'recruiter_response_rate': rs.get('recruiter_response_rate'),
        'avg_response_time_hours': rs.get('avg_response_time_hours'),
        'connection_count': rs.get('connection_count'),
        'endorsements_received': rs.get('endorsements_received'),
        'notice_period_days': rs.get('notice_period_days'),
        'salary_min_lpa': sal.get('min'),
        'salary_max_lpa': sal.get('max'),
        'preferred_work_mode': rs.get('preferred_work_mode'),
        'willing_to_relocate': rs.get('willing_to_relocate'),
        'github_activity_score': rs.get('github_activity_score'),
        'profile_views_30d': rs.get('profile_views_received_30d'),
        'applications_30d': rs.get('applications_submitted_30d'),
        'search_appearances_30d': rs.get('search_appearance_30d'),
        'saved_by_recruiters_30d': rs.get('saved_by_recruiters_30d'),
        'interview_completion_rate': rs.get('interview_completion_rate'),
        'offer_acceptance_rate': rs.get('offer_acceptance_rate'),
        'verified_email': rs.get('verified_email'),
        'verified_phone': rs.get('verified_phone'),
        'linkedin_connected': rs.get('linkedin_connected'),
    }


df = pd.DataFrame([flatten(c) for c in candidates])
print(f"DataFrame shape: {df.shape}")
print(df.head(3))


# =============================================================================
# Step 3 - Data quality: nulls and basic stats
# =============================================================================

# Null counts
null_counts = df.isnull().sum().sort_values(ascending=False)
null_counts = null_counts[null_counts > 0]
print("Columns with nulls:")
print(null_counts.to_string())

# Numeric column stats
num_cols = [
    'years_of_experience', 'n_jobs', 'total_career_months', 'avg_job_tenure_months',
    'n_skills', 'n_expert_skills', 'n_advanced_skills', 'avg_skill_duration_months',
    'profile_completeness', 'days_inactive', 'recruiter_response_rate',
    'avg_response_time_hours', 'connection_count', 'endorsements_received',
    'notice_period_days', 'salary_min_lpa', 'salary_max_lpa',
    'github_activity_score', 'profile_views_30d', 'interview_completion_rate',
    'offer_acceptance_rate'
]
print(df[num_cols].describe().round(2))

# Distributions: key numeric fields
fig, axes = plt.subplots(3, 4, figsize=(18, 12))
axes = axes.flatten()

plot_cols = [
    ('years_of_experience', 'Years of Experience'),
    ('n_jobs', 'Number of Jobs'),
    ('avg_job_tenure_months', 'Avg Job Tenure (months)'),
    ('n_skills', 'Number of Skills'),
    ('n_expert_skills', 'Expert Skills Count'),
    ('avg_skill_duration_months', 'Avg Skill Duration (months)'),
    ('profile_completeness', 'Profile Completeness (%)'),
    ('recruiter_response_rate', 'Recruiter Response Rate'),
    ('github_activity_score', 'GitHub Activity Score'),
    ('notice_period_days', 'Notice Period (days)'),
    ('interview_completion_rate', 'Interview Completion Rate'),
    ('offer_acceptance_rate', 'Offer Acceptance Rate'),
]

for ax, (col, label) in zip(axes, plot_cols):
    data = df[col].dropna()
    ax.hist(data, bins=30, color='steelblue', edgecolor='white', linewidth=0.5)
    ax.set_title(label, fontsize=10, fontweight='bold')
    ax.set_xlabel('')
    med = data.median()
    ax.axvline(med, color='red', linestyle='--', linewidth=1.2, label=f'median={med:.1f}')
    ax.legend(fontsize=8)

plt.suptitle('Distribution of Key Candidate Fields', fontsize=14, fontweight='bold', y=1.01)
plt.tight_layout()
plt.show()


# =============================================================================
# Step 4 - Understand categorical fields
# =============================================================================

print("Top 30 current titles:")
print(df['current_title'].value_counts().head(30).to_string())

print("Top 20 industries:")
print(df['current_industry'].value_counts().head(20).to_string())
print()
print("Top 20 countries:")
print(df['country'].value_counts().head(20).to_string())

# Work mode preference + relocation
fig, axes = plt.subplots(1, 3, figsize=(14, 4))

df['preferred_work_mode'].value_counts().plot(kind='bar', ax=axes[0], color='steelblue')
axes[0].set_title('Preferred Work Mode')
axes[0].set_xlabel('')

df['willing_to_relocate'].value_counts().plot(kind='bar', ax=axes[1], color='coral')
axes[1].set_title('Willing to Relocate')
axes[1].set_xlabel('')

df['open_to_work'].value_counts().plot(kind='bar', ax=axes[2], color='mediumseagreen')
axes[2].set_title('Open to Work Flag')
axes[2].set_xlabel('')

plt.tight_layout()
plt.show()

print(f"Open to work: {df['open_to_work'].sum()} / {len(df)} ({df['open_to_work'].mean():.1%})")
print(f"Willing to relocate: {df['willing_to_relocate'].sum()} / {len(df)} ({df['willing_to_relocate'].mean():.1%})")

# Skill names - most common
all_skill_names = []
for c in candidates:
    for s in c.get('skills', []):
        name = (s.get('name') or '').strip()
        if name:
            all_skill_names.append(name)

skill_counts = Counter(all_skill_names)
top_skills = skill_counts.most_common(40)

fig, ax = plt.subplots(figsize=(10, 8))
names, counts = zip(*top_skills)
ax.barh(names[::-1], counts[::-1], color='steelblue')
ax.set_title('Top 40 Most Common Skills', fontweight='bold')
ax.set_xlabel('Count')
plt.tight_layout()
plt.show()

print("\nTop 40 skills:")
for name, count in top_skills:
    print(f"  {count:4d}  {name}")

# Skill proficiency breakdown
all_proficiencies = []
for c in candidates:
    for s in c.get('skills', []):
        p = s.get('proficiency', 'unknown')
        all_proficiencies.append(p)

prof_counts = Counter(all_proficiencies)
print("Proficiency distribution across all skills:")
for level in ['beginner', 'intermediate', 'advanced', 'expert']:
    count = prof_counts.get(level, 0)
    pct = count / len(all_proficiencies) * 100
    print(f"  {level:15s}: {count:6,d}  ({pct:.1f}%)")


# =============================================================================
# Step 5 - The 23 Redrob Signals: deep dive
# =============================================================================

# Signal correlation heatmap
signal_cols = [
    'profile_completeness', 'recruiter_response_rate', 'avg_response_time_hours',
    'connection_count', 'endorsements_received', 'notice_period_days',
    'github_activity_score', 'profile_views_30d', 'applications_30d',
    'search_appearances_30d', 'saved_by_recruiters_30d',
    'interview_completion_rate', 'offer_acceptance_rate', 'days_inactive'
]

corr = df[signal_cols].corr()
fig, ax = plt.subplots(figsize=(12, 9))
mask = np.triu(np.ones_like(corr, dtype=bool))
sns.heatmap(corr, mask=mask, annot=True, fmt='.2f', cmap='RdBu_r',
            center=0, vmin=-1, vmax=1, ax=ax, linewidths=0.5)
ax.set_title('Signal Correlation Matrix', fontsize=13, fontweight='bold')
plt.tight_layout()
plt.show()

# Notice period distribution
fig, axes = plt.subplots(1, 2, figsize=(13, 4))

df['notice_period_days'].dropna().hist(bins=20, ax=axes[0], color='coral', edgecolor='white')
axes[0].set_title('Notice Period (days)')
axes[0].set_xlabel('Days')

np_counts = df['notice_period_days'].value_counts().sort_index()
np_counts.plot(kind='bar', ax=axes[1], color='coral')
axes[1].set_title('Notice Period - exact values')
axes[1].set_xlabel('Days')

plt.tight_layout()
plt.show()
print(df['notice_period_days'].value_counts().sort_index().to_string())

# GitHub activity score breakdown
gh = df['github_activity_score'].dropna()
print(f"GitHub score - min: {gh.min():.1f}, max: {gh.max():.1f}, median: {gh.median():.1f}")
print(f"Score = 0   : {(gh == 0).sum()} ({(gh==0).mean():.1%}) - no GitHub activity")
print(f"Score > 50  : {(gh > 50).sum()} ({(gh>50).mean():.1%}) - strong GitHub")
print(f"Score > 80  : {(gh > 80).sum()} ({(gh>80).mean():.1%}) - very active")

gh.hist(bins=25, color='mediumseagreen', edgecolor='white', figsize=(8, 3))
plt.title('GitHub Activity Score Distribution')
plt.xlabel('Score')
plt.show()

# Activity recency
di = df['days_inactive'].replace(9999, np.nan).dropna()
print(f"Days inactive - min: {di.min():.0f}, max: {di.max():.0f}, median: {di.median():.0f}")
print(f"Active last 7d   : {(di <= 7).sum()}")
print(f"Active last 30d  : {(di <= 30).sum()}")
print(f"Active last 90d  : {(di <= 90).sum()}")
print(f"Inactive 180d+   : {(di > 180).sum()}")

di.clip(upper=365).hist(bins=30, color='steelblue', edgecolor='white', figsize=(8, 3))
plt.title('Days Inactive (capped at 365)')
plt.xlabel('Days')
plt.show()


# =============================================================================
# Step 6 - Spot honeypots
# =============================================================================

# Flag 1: Stated YOE vs summed career history
def yoe_vs_career(c):
    stated = c['profile'].get('years_of_experience') or 0
    summed = sum(j.get('duration_months') or 0 for j in c.get('career_history', [])) / 12
    if stated > 0 and summed > 0:
        return stated / summed
    return 1.0  # can't tell


df['yoe_vs_career_ratio'] = [yoe_vs_career(c) for c in candidates]

print("YOE-to-career-history ratio (>2.5 = suspicious):")
suspicious_yoe = df[df['yoe_vs_career_ratio'] > 2.5]
print(f"  Suspicious count: {len(suspicious_yoe)} / {len(df)} ({len(suspicious_yoe)/len(df):.1%})")
print(suspicious_yoe[['candidate_id', 'current_title', 'years_of_experience', 'yoe_vs_career_ratio']].head(10))


# Flag 2: Expert proficiency with 0 months duration
def expert_zero_months(c):
    return sum(1 for s in c.get('skills', [])
               if s.get('proficiency') == 'expert' and (s.get('duration_months') or 0) == 0)


df['n_expert_zero_duration'] = [expert_zero_months(c) for c in candidates]

print("Candidates with 'expert' skills but 0 months duration:")
ezo = df[df['n_expert_zero_duration'] >= 2]
print(f"  2+ such skills: {len(ezo)} candidates")
print(ezo[['candidate_id', 'current_title', 'n_expert_skills', 'n_expert_zero_duration']].head(10))


# Flag 3: Implausible expert skill count
print("Candidates with 10+ expert skills (implausible diversity):")
many_experts = df[df['n_expert_skills'] >= 10]
print(f"  Count: {len(many_experts)}")
print(many_experts[['candidate_id', 'current_title', 'n_expert_skills', 'n_skills']].head(10))


# Flag 4: Open to work but inactive 1 year+
ghost_candidates = df[(df['open_to_work'] == True) & (df['days_inactive'] > 365)]
print(f"'Open to work' but inactive 365+ days: {len(ghost_candidates)}")
print(ghost_candidates[['candidate_id', 'current_title', 'open_to_work', 'days_inactive']].head(10))


# Flag 5: 0% response rate + 100% offer acceptance (impossible combo)
impossible = df[
    (df['recruiter_response_rate'] == 0) &
    (df['offer_acceptance_rate'] == 1.0)
]
print(f"Response rate=0 AND offer acceptance=100%: {len(impossible)} candidates")
print(impossible[['candidate_id', 'recruiter_response_rate', 'offer_acceptance_rate']].head())


# Overall honeypot summary
def count_honeypot_flags(c, df_row):
    flags = 0
    if df_row['yoe_vs_career_ratio'] > 2.5:
        flags += 2
    if df_row['n_expert_zero_duration'] >= 3:
        flags += 2
    elif df_row['n_expert_zero_duration'] >= 1:
        flags += 1
    if df_row['n_expert_skills'] >= 10:
        flags += 2
    elif df_row['n_expert_skills'] >= 7:
        flags += 1
    if df_row['open_to_work'] and df_row['days_inactive'] > 365:
        flags += 1
    if df_row['recruiter_response_rate'] == 0 and df_row['offer_acceptance_rate'] == 1.0:
        flags += 2
    return flags


df['honeypot_flags'] = [count_honeypot_flags(candidates[i], df.iloc[i]) for i in range(len(candidates))]

flag_dist = df['honeypot_flags'].value_counts().sort_index()
print("Honeypot flag distribution (0=clean, 4+=disqualify):")
for flags, count in flag_dist.items():
    label = 'CLEAN' if flags == 0 else ('LOW RISK' if flags == 1 else ('SUSPICIOUS' if flags < 4 else 'DISQUALIFY'))
    print(f"  {flags} flags: {count:4d} candidates  [{label}]")

df['honeypot_flags'].hist(bins=range(0, df['honeypot_flags'].max() + 2),
                           color='tomato', edgecolor='white', figsize=(8, 3))
plt.title('Honeypot Flag Count Distribution')
plt.xlabel('Flags')
plt.show()


# =============================================================================
# Step 7 - Read real profiles: good vs bad
# =============================================================================

def print_profile(c, idx=None):
    p = c['profile']
    rs = c['redrob_signals']
    print('=' * 65)
    if idx is not None:
        print(f'  INDEX: {idx}')
    print(f'  ID:       {c["candidate_id"]}')
    print(f'  Name:     {p.get("anonymized_name")}')
    print(f'  Title:    {p.get("current_title")} @ {p.get("current_company")}')
    print(f'  Industry: {p.get("current_industry")}')
    print(f'  Location: {p.get("location")}, {p.get("country")}')
    print(f'  YOE:      {p.get("years_of_experience")} years')
    summary = (p.get('summary') or '')[:250]
    print(f'  Summary:  {summary}...' if len(p.get('summary', '')) > 250 else f'  Summary:  {summary}')
    print()
    print('  CAREER HISTORY:')
    for j in c.get('career_history', []):
        print(f'    - {j.get("title")} @ {j.get("company")} ({j.get("duration_months")}mo) [{j.get("industry")}]')
    print()
    print('  SKILLS (top 8 by duration):')
    sorted_skills = sorted(c.get('skills', []), key=lambda s: s.get('duration_months') or 0, reverse=True)[:8]
    for s in sorted_skills:
        print(f'    - {s["name"]:30s} {s.get("proficiency","?"):14s} {s.get("duration_months",0):3d}mo  {s.get("endorsements",0)} endorsements')
    print()
    print('  EDUCATION:')
    for e in c.get('education', []):
        print(f'    - {e.get("degree")} in {e.get("field_of_study")} @ {e.get("institution")} [{e.get("tier")}]')
    print()
    print('  SIGNALS:')
    print(f'    Open to work:        {rs.get("open_to_work_flag")}')
    print(f'    Last active:         {rs.get("last_active_date")}')
    print(f'    Response rate:       {rs.get("recruiter_response_rate")}')
    print(f'    GitHub score:        {rs.get("github_activity_score")}')
    print(f'    Notice period:       {rs.get("notice_period_days")} days')
    print(f'    Interview complete:  {rs.get("interview_completion_rate")}')
    print(f'    Offer acceptance:    {rs.get("offer_acceptance_rate")}')
    print(f'    Verified email/phone:{rs.get("verified_email")} / {rs.get("verified_phone")}')
    sal = rs.get('expected_salary_range_inr_lpa') or {}
    print(f'    Expected salary:     Rs.{sal.get("min")}-{sal.get("max")} LPA')
    print()


print("print_profile() helper ready.")

# Look at the top AI/ML titles in our sample
AI_TITLE = re.compile(
    r'\b(machine.?learning|ml|ai|nlp|search|retrieval|ranking|'
    r'recommendation|embedding|llm|data.?scien|research.?engineer)\b',
    re.IGNORECASE
)
ai_candidates = [
    (i, c) for i, c in enumerate(candidates)
    if AI_TITLE.search(c['profile'].get('current_title', ''))
]
print(f"Candidates with AI/ML in current title: {len(ai_candidates)} / {len(candidates)}")
for i, c in ai_candidates[:5]:
    print_profile(c, idx=i)

# Look at clearly bad candidates (wrong domain)
BAD_TITLE = re.compile(
    r'\b(marketing|accountant|civil.?engineer|mechanical|graphic.?design|'
    r'content.?writer|customer.?support|sales|hr.?manager)\b',
    re.IGNORECASE
)
bad_candidates = [
    (i, c) for i, c in enumerate(candidates)
    if BAD_TITLE.search(c['profile'].get('current_title', ''))
]
print(f"Clearly off-domain candidates: {len(bad_candidates)} / {len(candidates)}")
for i, c in bad_candidates[:2]:
    print_profile(c, idx=i)

# Spot a likely keyword stuffer (high skill count but bad title)
stuffers = df[
    (df['n_expert_skills'] >= 5) &
    (~df['current_title'].str.contains('engineer|scien|developer|architect|analyst', case=False, na=False))
].head(3)
print("Potential keyword stuffers:")
print(stuffers[['candidate_id', 'current_title', 'n_skills', 'n_expert_skills']])
for cid in stuffers['candidate_id'].values:
    c = next(x for x in candidates if x['candidate_id'] == cid)
    print_profile(c)

# Spot a likely honeypot
high_flag = df[df['honeypot_flags'] >= 4]['candidate_id'].values
if len(high_flag) > 0:
    c = next(x for x in candidates if x['candidate_id'] == high_flag[0])
    print("HONEYPOT CANDIDATE:")
    print_profile(c)
else:
    print("No hard honeypots in this sample - try loading more candidates")


# =============================================================================
# Step 8 - Save EDA summary to a CSV for reference
# =============================================================================

summary_cols = [
    'candidate_id', 'current_title', 'country', 'years_of_experience',
    'n_skills', 'n_expert_skills', 'profile_completeness',
    'days_inactive', 'recruiter_response_rate', 'github_activity_score',
    'notice_period_days', 'open_to_work', 'honeypot_flags'
]
Path('../artifacts').mkdir(parents=True, exist_ok=True)
df[summary_cols].to_csv('../artifacts/eda_summary.csv', index=False)
print("Saved artifacts/eda_summary.csv")

# After running everything above, jot down your own takeaways:
# - Which fields have nulls, and how will you handle them?
# - What's the most common job title? What % of candidates are AI/ML-titled?
# - Is the GitHub activity score mostly 0? What's "good" for this dataset?
# - What's the honeypot rate at 4+ flags?
# - Do any scoring weights need rethinking after seeing real data?

"""
features.py — v2 (post-EDA fixes)

Key changes from EDA findings:
- expert skills are 0.1% of data — treat 'advanced' as top tier
- github_activity_score = -1 means "not linked", not bad → neutral weight
- offer_acceptance_rate = -1 means no data → skip it
- notice period penalty starts at 90+ days (median=90), not 30+
- top skills in dataset are off-domain (JS, Agile, SAP) — core AI skill matching matters more
- no YOE/career-history ratio honeypots found — keep but lower sensitivity
"""

from __future__ import annotations
import re
from datetime import date, datetime
from typing import Any

# ─────────────────────────────────────────────
#  JD-derived constants
# ─────────────────────────────────────────────

GOOD_TITLES = re.compile(
    r"\b(machine.?learning|ml.?engineer|ai.?engineer|applied.?scien|"
    r"nlp|search.?engineer|retrieval|ranking|recommendation|embedding|"
    r"llm|generative.?ai|inference|research.?engineer|data.?scien|"
    r"backend.?engineer|data.?engineer|software.?engineer|"
    r"senior.?engineer|lead.?engineer|principal.?engineer|staff.?engineer|"
    r"full.?stack|platform.?engineer|algorithm|ai.?specialist)\b",
    re.IGNORECASE,
)

BAD_TITLES = re.compile(
    r"\b(marketing|accountant|civil.?engineer|mechanical.?engineer|"
    r"graphic.?design|content.?writer|customer.?support|sales.?executive|"
    r"hr.?manager|human.?resource|recruiter|finance|legal|supply.?chain|"
    r"operations.?manager|project.?manager|qa.?engineer)\b",
    re.IGNORECASE,
)

SERVICES_COMPANIES = re.compile(
    r"\b(tcs|tata.?consultancy|infosys|wipro|accenture|cognizant|capgemini|"
    r"hcl|tech.?mahindra|mphasis|mindtree|hexaware|ltimindtree|"
    r"l&t.?infotech|niit|mastech|patni)\b",
    re.IGNORECASE,
)

# Core AI/ML skills from the JD — used for matching
# EDA showed these skills DO exist in the data (Milvus, FAISS, Sentence Transformers etc.)
CORE_AI_SKILLS = {
    "sentence-transformers", "sentence_transformers", "embeddings", "embedding",
    "vector database", "vector search", "semantic search", "hybrid search",
    "faiss", "pinecone", "weaviate", "qdrant", "milvus", "opensearch",
    "elasticsearch", "retrieval", "ranking", "reranking", "re-ranking",
    "ndcg", "mrr", "map", "evaluation framework",
    "lora", "qlora", "peft", "fine-tuning", "fine tuning", "fine-tuning llms",
    "learning to rank", "xgboost", "neural ranking",
    "rag", "retrieval augmented generation",
    "bert", "bge", "e5", "openai embeddings",
    "nlp", "information retrieval", "recommendation system",
    "recommendation engine", "llm", "large language model",
    "transformers", "hugging face", "hugging face transformers", "pytorch", "tensorflow",
    "information retrieval", "vector search",
}

# EDA confirmed these are common in the dataset — they signal keyword stuffing
# when someone has them but no real AI experience
KEYWORD_FLUFF = {
    "langchain", "chatgpt", "openai api", "gpt-4", "gpt4", "chatbot",
    "prompt engineering", "no-code", "zapier", "content writing",
    "agile", "six sigma", "sap", "salesforce crm", "illustrator",
}

PREFERRED_LOCATIONS = re.compile(
    r"\b(pune|noida|delhi|gurugram|gurgaon|ncr|hyderabad|mumbai|"
    r"bangalore|bengaluru|chennai|india)\b",
    re.IGNORECASE,
)

# EDA: advanced is the real top tier (expert = 0.1% of all skills)
PROFICIENCY_WEIGHT = {
    "beginner":     0.10,
    "intermediate": 0.45,
    "advanced":     1.00,   # treat as top tier (was 0.75 before EDA)
    "expert":       1.00,   # same as advanced since it's almost non-existent
}

TIER_SCORE = {
    "tier_1": 1.0, "tier_2": 0.75, "tier_3": 0.50,
    "tier_4": 0.25, "unknown": 0.35,
}

CS_FIELDS = re.compile(
    r"\b(computer|software|information|data|electrical|electronics|"
    r"mathematics|statistics|machine.?learning|ai|engineering)\b",
    re.IGNORECASE,
)

TECH_INDUSTRY = re.compile(
    r"\b(technology|software|saas|fintech|edtech|healthtech|ai|ml|"
    r"data|cloud|internet|e.?commerce|startup|product|food.?delivery|"
    r"conversational.?ai|adtech)\b",
    re.IGNORECASE,
)

# Scoring component weights (must sum to 1.0)
WEIGHTS = {
    "title":      0.25,
    "career":     0.30,
    "skill":      0.25,
    "experience": 0.10,
    "location":   0.05,
    "education":  0.05,
}

# ─────────────────────────────────────────────
#  Helpers
# ─────────────────────────────────────────────

def _days_since(date_str: str | None, ref: date | None = None) -> int:
    if not date_str:
        return 9999
    ref = ref or date.today()
    try:
        d = datetime.strptime(date_str[:10], "%Y-%m-%d").date()
        return (ref - d).days
    except Exception:
        return 9999

def _clamp(v: float, lo: float = 0.0, hi: float = 1.0) -> float:
    return max(lo, min(hi, v))

def _safe_signal(value, default: float = 0.0) -> float:
    """Return default if value is None, negative (sentinel -1), or missing."""
    if value is None or value < 0:
        return default
    return float(value)

# ─────────────────────────────────────────────
#  Honeypot detector
# ─────────────────────────────────────────────

def honeypot_penalty(candidate: dict[str, Any]) -> float:
    """
    Returns 0.0 for obvious fakes, 1.0 for clean profiles.
    EDA showed no honeypots in first 1000 — thresholds are kept but sensitivity tuned down.
    """
    profile = candidate.get("profile", {})
    career  = candidate.get("career_history", [])
    skills  = candidate.get("skills", [])
    signals = candidate.get("redrob_signals", {})
    flags   = 0

    # 1. Stated YOE much larger than summed career history
    stated_yoe    = profile.get("years_of_experience", 0) or 0
    summed_months = sum(r.get("duration_months", 0) or 0 for r in career)
    if stated_yoe > 0 and summed_months > 0:
        ratio = stated_yoe / max(summed_months / 12, 0.1)
        if ratio > 3.0:    # loosened from 2.5 — EDA showed 0 violations in 1000
            flags += 2

    # 2. "Expert" proficiency with 0 months duration
    # EDA: expert is extremely rare — any expert+0months is suspicious
    expert_zero = [s for s in skills
                   if s.get("proficiency") == "expert"
                   and (s.get("duration_months") or 0) == 0]
    if len(expert_zero) >= 2: flags += 2
    elif len(expert_zero) >= 1: flags += 1

    # 3. Implausible expert skill count
    # EDA: max was 5 expert skills in 1000 candidates — 6+ is suspicious
    expert_count = sum(1 for s in skills if s.get("proficiency") == "expert")
    if expert_count >= 6: flags += 2
    elif expert_count >= 4: flags += 1

    # 4. Open to work but inactive for a year
    if signals.get("open_to_work_flag") and _days_since(signals.get("last_active_date")) > 365:
        flags += 1

    # 5. Contradictory signals: 0% response rate but 100% offer acceptance
    # EDA: offer_acceptance -1 is "no data", not 0 — use _safe_signal
    rrr = signals.get("recruiter_response_rate", -1)
    oar = signals.get("offer_acceptance_rate", -1)
    if rrr == 0 and oar == 1.0:   # both must be real values
        flags += 2

    if flags >= 4: return 0.0
    if flags >= 3: return 0.15
    if flags >= 2: return 0.40
    if flags >= 1: return 0.75
    return 1.0

# ─────────────────────────────────────────────
#  Title score
# ─────────────────────────────────────────────

def title_score(candidate: dict[str, Any]) -> float:
    profile = candidate.get("profile", {})
    career  = candidate.get("career_history", [])

    all_titles = [profile.get("current_title", "")] + [j.get("title", "") for j in career]
    combined   = " ".join(all_titles)

    good_hits = len(GOOD_TITLES.findall(combined))
    bad_hits  = len(BAD_TITLES.findall(combined))

    # Current title weighted more heavily
    current = profile.get("current_title", "")
    if GOOD_TITLES.search(current): good_hits += 2
    if BAD_TITLES.search(current):  bad_hits  += 2

    return _clamp(good_hits * 0.25 - bad_hits * 0.30)

# ─────────────────────────────────────────────
#  Career score
# ─────────────────────────────────────────────

def career_score(candidate: dict[str, Any]) -> float:
    career = candidate.get("career_history", [])
    if not career:
        return 0.0

    total_months = ai_product_months = services_months = 0
    tenures = []

    for job in career:
        dur      = job.get("duration_months") or 0
        company  = job.get("company", "")
        industry = job.get("industry", "")
        title    = job.get("title", "")
        desc     = (job.get("description") or "").lower()

        total_months += dur
        tenures.append(dur)

        is_services    = bool(SERVICES_COMPANIES.search(company))
        is_good_title  = bool(GOOD_TITLES.search(title))
        is_tech_ind    = bool(TECH_INDUSTRY.search(industry))
        has_ai_content = any(kw in desc for kw in [
            "embedding", "retrieval", "ranking", "nlp", "machine learning",
            "vector", "search", "recommendation", "llm", "deep learning",
            "fine-tun", "transformer",
        ])

        if is_services:
            services_months += dur
        elif is_good_title or is_tech_ind or has_ai_content:
            ai_product_months += dur

    if total_months == 0:
        return 0.0

    ai_ratio       = ai_product_months / total_months
    services_ratio = services_months   / total_months

    # EDA: avg tenure median = 27.8 months, min = 10 months
    # Stability: <18 months avg = job-hopper; 30+ = stable
    avg_tenure = sum(tenures) / len(tenures) if tenures else 0
    stability  = _clamp((avg_tenure - 12) / 24)   # 12mo → 0, 36mo → 1

    return _clamp(
        ai_ratio       * 0.55 +
        (1 - services_ratio) * 0.25 +
        stability      * 0.20
    )

# ─────────────────────────────────────────────
#  Skill score
# ─────────────────────────────────────────────

def skill_score(candidate: dict[str, Any]) -> float:
    skills      = candidate.get("skills", [])
    signals     = candidate.get("redrob_signals", {})
    assessments = signals.get("skill_assessment_scores") or {}

    ai_score    = 0.0
    fluff_count = 0

    for s in skills:
        name_lower  = (s.get("name") or "").lower()
        proficiency = PROFICIENCY_WEIGHT.get(s.get("proficiency", "beginner"), 0.10)

        # EDA: avg skill duration = 17.3 months, max ~40
        # Duration multiplier: 0mo → 0.3, 24mo+ → 1.0
        dur_months = s.get("duration_months") or 0
        dur_mult   = _clamp(0.3 + dur_months / 28)

        # Endorsement multiplier: 0 → 1.0, 50+ → 1.4
        endorsements = min(s.get("endorsements") or 0, 50)
        end_mult     = 1.0 + (endorsements / 125)

        if any(core in name_lower for core in CORE_AI_SKILLS):
            # Bonus if there's a verified assessment score for this skill
            assess_bonus = 0.0
            for ak, av in assessments.items():
                if ak.lower() in name_lower or name_lower in ak.lower():
                    # assessment score 0-100 → 0 to 0.3 bonus
                    assess_bonus = min(_safe_signal(av, 0) / 333, 0.30)
                    break
            ai_score += proficiency * dur_mult * end_mult + assess_bonus

        # EDA confirmed: Content Writing, Agile, SAP, Six Sigma etc. are fluff in this context
        if any(fluff in name_lower for fluff in KEYWORD_FLUFF):
            fluff_count += 1

    # Normalise: expect ~8–10 strong AI skills for a great candidate
    normalised    = _clamp(ai_score / 10.0)
    fluff_penalty = _clamp(1.0 - fluff_count * 0.08)

    return normalised * fluff_penalty

# ─────────────────────────────────────────────
#  Experience score
# ─────────────────────────────────────────────

def experience_score(candidate: dict[str, Any]) -> float:
    """
    EDA: median YOE = 6.3, range 1.1–15.
    JD sweet spot: 5–9 years. <3 too junior, >12 over-qualified.
    """
    yoe = candidate.get("profile", {}).get("years_of_experience") or 0
    if yoe < 2:    return 0.10
    if yoe < 4:    return 0.35 + (yoe - 2) * 0.10   # 0.35 → 0.55
    if yoe <= 9:   return 0.60 + (yoe - 4) * 0.06   # 0.60 → 0.90
    if yoe <= 12:  return 0.88 - (yoe - 9) * 0.04   # 0.88 → 0.76
    return 0.70

# ─────────────────────────────────────────────
#  Location score
# ─────────────────────────────────────────────

def location_score(candidate: dict[str, Any]) -> float:
    """
    EDA: 75.9% are in India already — location is less of a differentiator than expected.
    Willing to relocate = 29.8%.
    """
    profile  = candidate.get("profile", {})
    signals  = candidate.get("redrob_signals", {})
    location = (profile.get("location") or "") + " " + (profile.get("country") or "")

    if PREFERRED_LOCATIONS.search(location):
        return 1.0
    if signals.get("willing_to_relocate"):
        return 0.60
    if "india" not in location.lower():
        return 0.25   # outside India, not willing to relocate
    return 0.50

# ─────────────────────────────────────────────
#  Education score
# ─────────────────────────────────────────────

def education_score(candidate: dict[str, Any]) -> float:
    edu = candidate.get("education", [])
    if not edu:
        return 0.30
    best = 0.0
    for e in edu:
        t = TIER_SCORE.get(e.get("tier", "unknown"), 0.35)
        f = 0.15 if CS_FIELDS.search(e.get("field_of_study") or "") else 0.0
        best = max(best, t + f)
    return _clamp(best)

# ─────────────────────────────────────────────
#  Availability multiplier
# ─────────────────────────────────────────────

def availability_multiplier(candidate: dict[str, Any]) -> float:
    """
    EDA key findings applied:
    - github_activity_score: -1 = not linked (neutral 0.5), not bad
    - offer_acceptance_rate: -1 = no data (skip it entirely)
    - notice_period: clusters at 30/60/90/120/150 — penalty starts at 90+ (median)
    - days_inactive: fairly uniform 21–261, median 128 days
    - open_to_work: only 34.6% True — strong differentiator, keep high weight
    """
    signals = candidate.get("redrob_signals", {})

    # Recency: median inactive = 128 days. 30d → 1.0, 200d → 0.2
    days_inactive = _days_since(signals.get("last_active_date"))
    recency = _clamp(1.0 - days_inactive / 200)

    # Open to work (34.6% True → strong differentiator)
    otw = 1.0 if signals.get("open_to_work_flag") else 0.45

    # Recruiter responsiveness (median ~0.4, fairly spread — useful signal)
    rrr = _safe_signal(signals.get("recruiter_response_rate"), default=0.3)

    # Interview reliability (median ~0.62, range 0.3–1.0)
    icr = _safe_signal(signals.get("interview_completion_rate"), default=0.5)

    # Notice period:
    # EDA clusters: 30=great, 60=fine, 90=median/ok, 120=penalty, 150=big penalty
    np_days = signals.get("notice_period_days") or 90
    if np_days <= 30:   notice = 1.00
    elif np_days <= 60: notice = 0.85
    elif np_days <= 90: notice = 0.65   # median — neutral
    elif np_days <= 120: notice = 0.40
    else:               notice = 0.20   # 150 days

    # GitHub score: EDA showed -1 = not linked (67% of candidates)
    # Treat -1 as neutral (0.5), not penalise. Only 3.9% have score > 50.
    gh_raw = signals.get("github_activity_score")
    if gh_raw is None or gh_raw < 0:
        github = 0.50    # neutral — no data, not a penalty
    else:
        github = _clamp(gh_raw / 100)

    # NOTE: offer_acceptance_rate intentionally excluded
    # EDA showed median = -1.0 (no data for most candidates)

    mult = (
        recency * 0.28 +
        otw     * 0.25 +
        rrr     * 0.20 +
        icr     * 0.15 +
        notice  * 0.07 +
        github  * 0.05
    )

    return _clamp(mult, 0.20, 1.0)

# ─────────────────────────────────────────────
#  Composite score
# ─────────────────────────────────────────────

def structured_score(candidate: dict[str, Any]) -> dict[str, float]:
    t  = title_score(candidate)
    c  = career_score(candidate)
    s  = skill_score(candidate)
    e  = experience_score(candidate)
    l  = location_score(candidate)
    ed = education_score(candidate)

    composite = (
        t  * WEIGHTS["title"]      +
        c  * WEIGHTS["career"]     +
        s  * WEIGHTS["skill"]      +
        e  * WEIGHTS["experience"] +
        l  * WEIGHTS["location"]   +
        ed * WEIGHTS["education"]
    )

    return {
        "title_score":      round(t,  4),
        "career_score":     round(c,  4),
        "skill_score":      round(s,  4),
        "experience_score": round(e,  4),
        "location_score":   round(l,  4),
        "education_score":  round(ed, 4),
        "structured":       round(composite, 4),
    }


def final_score(
    candidate: dict[str, Any],
    embedding_sim: float = 0.0,
    embed_weight:  float = 0.25,
) -> tuple[float, dict[str, float]]:
    """Returns (score_0_to_1, component_dict)."""
    components = structured_score(candidate)
    hp = honeypot_penalty(candidate)
    av = availability_multiplier(candidate)

    raw   = components["structured"] * (1 - embed_weight) + embedding_sim * embed_weight
    score = _clamp(raw * hp * av)

    components.update({
        "embedding_sim":     round(embedding_sim, 4),
        "honeypot_mult":     round(hp, 4),
        "availability_mult": round(av, 4),
        "final":             round(score, 4),
    })
    return score, components

# ─────────────────────────────────────────────
#  Text document builder (for embedding)
# ─────────────────────────────────────────────

def build_candidate_doc(candidate: dict[str, Any]) -> str:
    parts = []
    p = candidate.get("profile", {})

    parts.append(p.get("headline") or "")
    parts.append(p.get("summary") or "")
    parts.append(
        f"Current: {p.get('current_title','')} at "
        f"{p.get('current_company','')} ({p.get('current_industry','')})"
    )

    for job in (candidate.get("career_history") or [])[:5]:
        parts.append(
            f"{job.get('title','')} at {job.get('company','')} "
            f"({job.get('industry','')}): {job.get('description','')}"
        )

    # Only advanced/expert skills for the embedding doc
    top_skills = [
        s.get("name", "") for s in (candidate.get("skills") or [])
        if s.get("proficiency") in ("advanced", "expert")
    ]
    if top_skills:
        parts.append("Advanced skills: " + ", ".join(top_skills))

    for cert in (candidate.get("certifications") or []):
        parts.append(f"Cert: {cert.get('name','')} by {cert.get('issuer','')}")

    return " | ".join(pt for pt in parts if pt.strip())

# ─────────────────────────────────────────────
#  Reasoning generator
# ─────────────────────────────────────────────

def generate_reasoning(candidate: dict[str, Any], components: dict[str, float]) -> str:
    p       = candidate.get("profile", {})
    signals = candidate.get("redrob_signals", {})

    title   = p.get("current_title") or "Unknown role"
    company = p.get("current_company") or ""
    yoe     = p.get("years_of_experience") or 0
    loc     = p.get("location") or p.get("country") or "Unknown"

    # Top AI skills (advanced/expert only)
    skills    = candidate.get("skills", [])
    ai_skills = [
        s["name"] for s in skills
        if any(c in (s.get("name") or "").lower() for c in CORE_AI_SKILLS)
        and s.get("proficiency") in ("advanced", "expert")
    ]
    top_skills_str = ", ".join(ai_skills[:3]) if ai_skills else "no core AI skills"

    # Availability signals
    rrr    = _safe_signal(signals.get("recruiter_response_rate"), -1)
    gh     = signals.get("github_activity_score")
    np_d   = signals.get("notice_period_days") or 0
    otw    = signals.get("open_to_work_flag", False)

    # Warnings
    warnings = []
    if components.get("honeypot_mult", 1.0) < 0.5:
        warnings.append("profile inconsistencies flagged")
    if components.get("availability_mult", 1.0) < 0.35:
        warnings.append("low availability signals")
    if np_d >= 120:
        warnings.append(f"{np_d}-day notice period")

    # Sentence 1: core fit
    company_str = f" @ {company}" if company else ""
    s1 = f"{title}{company_str}, {yoe:.1f}y exp; AI skills: {top_skills_str}; {loc}."

    # Sentence 2: availability / caution
    extras = []
    if otw:
        extras.append("actively looking")
    if rrr >= 0:
        extras.append(f"response rate {rrr:.0%}")
    if gh is not None and gh > 0:
        extras.append(f"GitHub {gh:.0f}/100")
    if warnings:
        extras.append("Caution: " + "; ".join(warnings))

    s2 = ("; ".join(extras)).capitalize() + "." if extras else ""

    return (s1 + " " + s2).strip()